/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { LazyIframe as LazyIframe } from './components/my-name/lazy-iframe';

interface HTMLLazyIframeElement extends LazyIframe, HTMLElement {
}
declare var HTMLLazyIframeElement: {
  prototype: HTMLLazyIframeElement;
  new (): HTMLLazyIframeElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "lazy-iframe": HTMLLazyIframeElement;
  }
  interface ElementTagNameMap {
      "lazy-iframe": HTMLLazyIframeElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "lazy-iframe": JSXElements.LazyIframeAttributes;
      }
  }
  namespace JSXElements {
      export interface LazyIframeAttributes extends HTMLAttributes {
        
          src?: any,
          title?: any
      }
  }
}

